package com.passnail.gui;

/**
 * Created by: Pszemko at wtorek, 02.03.2021 21:51
 * Project: passnail-client
 */
//TODO Javadoc
public class GuiConstants {

    public static final String EMPTY_HELP_MESSAGE = "";

    public static final String LOGOUT_BUTTON_HELP_MESSAGE = "Logout. Finishes your session and returns to the login screen.";

    public static final String SETTINGS_BUTTON_HELP_MESSAGE = "Settings. Opens a settings screen.";

    public static final String NEW_CREDENTIALS_BUTTON_HELP_MESSAGE = "Create new credentials. Lets you to generate and save a new password.";

    public static final String GENERATOR_SETTINGS_BUTTON_HELP_MESSAGE = "Generator settings. Lets you to configure the password generator.";

    public static final String SHOW_LIBRARY_BUTTON_HELP_MESSAGE = "Library. Opens a library of saved passwords.";

    public static final String QUICK_PASSWORD_BUTTON_HELP_MESSAGE = "Quick password. Generates a new password and copies it to the clipboard.";

    public static final String BACK_BUTTON_HELP_MESSAGE = "Back to main view.";

    public static final String GENERATE_NEW_PASSWORD_HELP_MESSAGE = "Generate a new password.";

    public static final String SAVE_CREDENTIALS_HELP_MESSAGE = "Save credentials to database.";

    public static final String CREDENTIALS_LIST_HELP_MESSAGE = "List of your saved credentials.";

    public static final String REFRESH_BUTTON_HELP_MESSAGE = "Refresh a list.";

    public static final String REMOVE_BUTTON_HELP_MESSAGE = "Remove credentials from the database.";

    public static final String EDIT_BUTTON_HELP_MESSAGE = "Edit credentials in the database.";

    public static final String ADD_BUTTON_HELP_MESSAGE = "Add new credentials to the database.";

    public static final String OPEN_BUTTON_HELP_MESSAGE = "Open a selected credentials.";

    public static final String BACK_TO_LIBRARY_BUTTON_HELP_MESSAGE = "Back to library.";

    public static final String PASSWORD_COPIED_NOTIFICATION_MESSAGE = "Password copied to the Clipboard!";

    public static final String LOGIN_COPIED_NOTIFICATION_MESSAGE = "Login copied to the Clipboard!";

    public static final String URL_COPIED_NOTIFICATION_MESSAGE = "URL copied to the Clipboard!";

    public static final String SHOW_CREDS_URL_HELP_MESSAGE = "URL. Click on the field to copy a value to the Clipboard.";

    public static final String SHOW_CREDS_LOGIN_HELP_MESSAGE = "Login. Click on the field to copy a value to the Clipboard.";

    public static final String SHOW_CREDS_PASSWORD_HELP_MESSAGE = "Password. Click on the field to copy a value to the Clipboard.";

    public static final String SHOW_CREDS_SHORT_NAME_HELP_MESSAGE = "Short Name.";

    public static final String SHOW_CREDS_DESCRIPTION_HELP_MESSAGE = "Description.";

    public static final String GENERATOR_SETTINGS_RESET_BUTTON_HELP_MESSAGE = "Click to reset the generator's setting to default values.";

    public static final String GENERATOR_SETTINGS_LENGTH_FIELD_HELP_MESSAGE = "A length of passwords being generated by generator.";

    public static final String GENERATOR_SETTINGS_UPPER_CASE_FIELD_HELP_MESSAGE = "A number of upper case letters contained in the generated passwords.";

    public static final String GENERATOR_SETTINGS_LOWER_CASE_FIELD_HELP_MESSAGE = "A number of lower case letters contained in the generated passwords.";

    public static final String GENERATOR_SETTINGS_SPECIAL_CHARACTERS_FIELD_HELP_MESSAGE = "A number of special characters contained in the generated passwords.";

    public static final String GENERATOR_SETTINGS_DIGITS_FIELD_HELP_MESSAGE = "A number of digits contained in the generated passwords.";

    public static final String GENERATOR_SETTINGS_SAVE_BUTTON_HELP_MESSAGE = "Click to save yous changes. Remember that properties need to be consistent!";

    public static final String EDITABLE_CREDENTIALS_SAVE_BUTTON_HELP_MESSAGE = "Save changes.";

    public static final String EDIT_CREDS_LOGIN_FIELD_HELP_MESSAGE = "Edit login.";

    public static final String EDIT_CREDS_PASSWORD_FIELD_HELP_MESSAGE = "Edit password.";

    public static final String EDIT_CREDS_URL_FIELD_MESSAGE_TEXT = "Edit url.";

    public static final String EDIT_CREDS_SHORT_NAME_FIELD_HELP_MESSAGE = "Edit short name.";

    public static final String EDIT_CREDS_DESCRIPTION_AREA_HELP_MESSAGE = "Edit description.";

    private GuiConstants() {
    }
}
